services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: ${ENVIRONMENT}
    container_name: makesimpleform-backend
    depends_on:
      - mongo
    command: ${DEV_COMMAND}
    ports:
      - "3000:3000"
    volumes:
      - .:/app:Z
    restart: always
    labels:
      - "traefik.enable=false"
    networks:
      - web

  mongo:
    image: mongo:6
    container_name: mongo-db
    ports:
      - "${MONGODB_PORT}:${MONGODB_PORT}"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
    volumes:
      - mongo-data:/data/db
    networks:
      - web

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-ui
    ports:
      - "${ME_PORT}:${ME_PORT}"
    environment:
      - ME_CONFIG_MONGODB_SERVER=${MONGODB_SERVER}
      - ME_CONFIG_MONGODB_PORT=${MONGODB_PORT}
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGODB_ROOT_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${ME_MONGODB_ADMINPASSWORD}
      - ME_CONFIG_BASICAUTH_USERNAME=${ME_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${ME_PASSWORD}
    depends_on:
      - mongo
    networks:
      - web

volumes:
  mongo-data:

networks:
  web:
    external: true