services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: ${ENVIRONMENT}
    container_name: makesimpleform-backend
    depends_on:
      - mongo
      - postgres
    command: ${DEV_COMMAND}
    ports:
      - '3000:3000'
    volumes:
      - .:/app:Z
    restart: always
    labels:
      - 'traefik.enable=false'
    networks:
      - web

  mongo:
    image: mongo:6
    container_name: mongo-db
    ports:
      - '${MONGODB_PORT}:${MONGODB_PORT}'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
    volumes:
      - mongo-data:/data/db
    networks:
      - web

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-ui
    ports:
      - '${ME_PORT}:${ME_PORT}'
    environment:
      - ME_CONFIG_MONGODB_SERVER=${MONGODB_SERVER}
      - ME_CONFIG_MONGODB_PORT=${MONGODB_PORT}
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGODB_ROOT_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${ME_MONGODB_ADMINPASSWORD}
      - ME_CONFIG_BASICAUTH_USERNAME=${ME_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${ME_PASSWORD}
    depends_on:
      - mongo
    networks:
      - web

  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - web

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-ui
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - '${PGADMIN_PORT}:80'
    depends_on:
      - postgres
    networks:
      - web

volumes:
  mongo-data:
  postgres-data:

networks:
  web:
    external: true
